name: Auto Deploy in VPS after Push in Production


on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy project with Gunicorn
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
            cd /mnt/data/THMDB
            git checkout main
            git pull 
            sudo systemctl restart THMDB.service
